// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_above_average_easy = "CgkI8ajHtfUZEAIQBg"; // <GPGSID>
        public const string leaderboard_score_ranking = "CgkI8ajHtfUZEAIQDw"; // <GPGSID>
        public const string achievement_meeting_the_creators = "CgkI8ajHtfUZEAIQAg"; // <GPGSID>
        public const string achievement_prideful = "CgkI8ajHtfUZEAIQDQ"; // <GPGSID>
        public const string achievement_ten_out_of_ten_hard = "CgkI8ajHtfUZEAIQCw"; // <GPGSID>
        public const string achievement_comeando_a_caminhada = "CgkI8ajHtfUZEAIQAA"; // <GPGSID>
        public const string achievement_ten_of_out_ten_easy = "CgkI8ajHtfUZEAIQCQ"; // <GPGSID>
        public const string achievement_tightfisted = "CgkI8ajHtfUZEAIQDA"; // <GPGSID>
        public const string achievement_above_average_hard = "CgkI8ajHtfUZEAIQCA"; // <GPGSID>
        public const string achievement_getting_the_hang_of_it_hard = "CgkI8ajHtfUZEAIQBQ"; // <GPGSID>
        public const string achievement_getting_the_hang_of_it_medium = "CgkI8ajHtfUZEAIQBA"; // <GPGSID>
        public const string achievement_ten_out_of_ten_medium = "CgkI8ajHtfUZEAIQCg"; // <GPGSID>
        public const string achievement_without_a_scratch = "CgkI8ajHtfUZEAIQDg"; // <GPGSID>
        public const string achievement_above_average_medium = "CgkI8ajHtfUZEAIQBw"; // <GPGSID>
        public const string achievement_getting_the_hang_of_it_easy = "CgkI8ajHtfUZEAIQAw"; // <GPGSID>

}

